### PR TITLE
[PROD-2034] License for SDK

### PR DESCRIPTION
**Pull request by lazaralex98**
- license file in root
- license description in source files where logic lies

### CODE REVIEW

**Comment by kargakis** [comment]
I guess instead of "fail" you mean "file" in the commit message.

Also [this place](https://github.com/ToucanProtocol/toucan-sdk/blob/b02c9e0e7bc0130844ec23280d97b97e89a4a252/package.json#L25) needs to be updated.

**Review by kargakis — DISMISSED** [review]
I guess instead of "fail" you mean "file" in the commit message.

Also [this place](https://github.com/ToucanProtocol/toucan-sdk/blob/b02c9e0e7bc0130844ec23280d97b97e89a4a252/package.json#L25) needs to be updated.

**Comment by lazaralex98** [comment]
Should we maybe add one of those badges for the license too? license

**Comment by kargakis** [comment]
A badge in the README would be nice too. I think it will change once the npm registry is updated.

**Review by kargakis — APPROVED** [review]

**Pull request merged**
